web:
  restart: always
  build: ./web
  expose:
    - "8001"
  links:
    - postgres:postgres
    - redis:redis
  env_file: .env
  command: production.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5433:5433"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6380:6380"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
